services:
  demo-generator-api:
    image: 754724220380.dkr.ecr.ap-southeast-2.amazonaws.com/watchme-api-demo-generator:latest
    container_name: demo-generator-api
    ports:
      - "127.0.0.1:8020:8020"
    env_file:
      - .env
    networks:
      - watchme-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  watchme-network:
    external: true
